# Generated by Django 4.2.4 on 2023-10-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todosapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task1",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="task1",
            name="start_date",
            field=models.DateField(),
        ),
    ]
