# Generated by Django 4.2.4 on 2023-10-09 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todosapp", "0002_alter_task1_end_date_alter_task1_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskCompletionstatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "completed_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="completions", to="todosapp.task1"
                    ),
                ),
            ],
        ),
    ]
