# Generated by Django 4.2.4 on 2023-10-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todosapp", "0004_taskcompletionstatus_is_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcompletionstatus",
            name="is_completed",
            field=models.CharField(
                choices=[("completed", "Completed"), ("uncompleted", "Uncompleted")],
                default="uncompleted",
                max_length=20,
            ),
        ),
    ]
