# Generated by Django 4.2.4 on 2023-10-09 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todosapp", "0005_alter_taskcompletionstatus_is_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskCreator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_tasks", models.ManyToManyField(related_name="creators", to="todosapp.task1")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
