# Generated by Django 4.2.4 on 2023-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.IntegerField(blank=True, null=True, verbose_name="Otp"),
        ),
    ]
